name: GISAID fetch and ingest (on branch)

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup
      shell: bash
      run: ./bin/setup-github-workflow

    - name: ingest
      shell: bash
      run: |
        ./bin/write-envdir env.d \
          AWS_DEFAULT_REGION \
          GISAID_API_ENDPOINT \
          GISAID_USERNAME_AND_PASSWORD \
          GITHUB_REF \
          SLACK_TOKEN

        stdbuf -i0 -o0 -e0 nextstrain build \
          --aws-batch \
          --no-download \
          --image nextstrain/ncov-ingest \
          --cpus 8 \
          --memory 15GiB \
          --exec env \
          . \
            stdbuf -i0 -o0 -e0 envdir env.d ingest-gisaid --fetch
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
